[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    'forge-std/=lib/forge-std/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/test-devtools-evm-foundry/=lib/devtools/packages/test-devtools-evm-foundry/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    'lz-evm-messagelib/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
    '@lz-oapp-v2/=lib/lz-oapp-v2/src/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
